language: php

php:
  - 7.4

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/clover.xml

after_success:
  - travis_retry vendor/bin/php-coveralls --coverage_clover build/clover.xml --json_path build/clover.json
